[build]
target = "arm-unknown-linux-gnueabi"

[alias]
xtask = "run --package xtask --target x86_64-unknown-linux-gnu --"

[target.arm-unknown-linux-gnueabi]
linker = "arm-frc2025-linux-gnueabi-gcc"
rustflags = ["-C", "target-cpu=cortex-a9"]
