[build]
target = "arm-unknown-linux-gnueabi"

[alias]
xtask = "run --package ferrobot-builder --release --target x86_64-unknown-linux-gnu --"
deploy = "xtask deploy"
simulate = "xtask simulate"

[target.arm-unknown-linux-gnueabi]
linker = "arm-frc2025-linux-gnueabi-gcc"
rustflags = ["-C", "target-cpu=cortex-a9"]
